### ISSUE TITLE
Epic: Wallet MVP

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/cred-wallet#56]
## User Features:
- Basic Display
  - [x] Display credential categories (initially by issuer)
  - [x] Basic display of credentials within category
  - [x] Look at detailed view of credential #64
- Request/Import
  - [x] Request credential with link #41 
  - [x] Request credential with QR code scan #52 
  - [x] Import existing credential (from file, URL, others?)
  - [x] Use DID (did:key) in credential request
- Share (tbd: email, linkedin?)
- Flexible branding? (e.g. DCC vs MIT/GA Tech/...
- App security and backup notes:
    - Master password
   - Biometric with pin code
   - Backup
     - use that pin code for generating backup (settings)
     - configure frequency of backup
     - backup accessible by id (with auth)
- Deploying/releasing: ios/android 

## Other notes (still iterating):
- oauth2 integration
- Storage
  - regular device encryption
